[uwsgi]
project = roulette
base = /var/www/roulette

chdir = %(base)
module = Donation_Manager.wsgi:application
home = %(base)/venv
master = true
processes = 4  # Количество процессов uWSGI
threads = 2 # Количество потоков на процесс
socket = %(base)/%(project).sock
chmod-socket = 660
vacuum = false
logto = /var/log/uwsgi/%(project).log
log-reopen = true
uid = roulette_user
# Группа www-data обычно используется для веб-серверов
gid = www-data
die-on-term = true
enable-inotify = true
touch-reload = /var/www/roulette/reload.file
