from django.urls import path
from .views import *

urlpatterns = [
    path('', main_page, name='main_page'),
    path('about/', about, name='about'),
    path('links/', links, name='links'),
    path('links_others/', links_others, name='links_others'),
    path('roulette/', roulette, name='roulette'),
    path('films/', films, name='films'),
    path('schedule/', schedule, name='schedule'),
    path('change_list/', change_list, name='change_list'),
    path('tg_rules/', tg_rules, name='tg_rules'),
    path('health/', health_check, name='health_check'),
    path('update_roulette/', update_roulette, name='update_roulette'),
    path('custom_admin_page/', custom_admin_page, name='custom_admin_page'),
    path('instruction/', instruction, name='instruction'),
    path('sitemap.xml', serve_sitemap, name='sitemap'),
    path('check-tg-user/', check_tg_user, name='check-tg-user'),
    path('get-tg-user-info/', get_tg_user_info, name='get_tg_user_info'),
    path('check-tg-limits/', check_tg_limits, name='check-tg-limits'),
    path('check-tg-limits-for-command/', check_tg_limits_for_command, name='check_tg_limits_for_command'),
    path('get-love/', get_love, name='get-love'),
    path('get-last-stream/', get_last_stream, name='get-last-stream'),
    path('tg-admin/', tg_admin, name='tg-admin'),
    path('get-tg-rules/', get_tg_rules, name='get_tg_rules'),
    path('get-driving-experience/', get_driving_experience, name='get_driving_experience'),
    path('get-tg-top-users/', get_tg_top_users, name='get_tg_top_users'),
    path('twitch_webhook/', twitch_webhook, name='twitch_webhook'),
    path('get-last-donate/', get_last_donate, name='get_last_donate'),
    path('get-last-tg-message/', get_last_tg_message, name='get_last_tg_message'),
    path('get-twitch-app-token/', get_twitch_app_token, name='get-twitch-app-token'),
    path('save_followers/', save_followers, name='save_followers'),
    path("twitch/auth/", twitch_auth, name="twitch_auth"),
    path("twitch/callback/", twitch_callback, name="twitch_callback"),
]
