# Generated by Django 5.2.1 on 2025-05-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True, verbose_name='id прокрута')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время прокрута')),
                ('username', models.CharField(db_index=True, max_length=30, verbose_name='Кому выпало')),
                ('result', models.CharField(max_length=50, verbose_name='Что выпало')),
                ('order', models.TextField(default='', verbose_name='Что заказал')),
                ('ready', models.BooleanField(max_length=30, verbose_name='Выполнили')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Прокрут рулетки',
                'verbose_name_plural': 'Результаты рулетки',
            },
        ),
    ]
