# Generated by Django 5.2.1 on 2025-05-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roulette',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='order',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Что заказал'),
        ),
    ]
