# Generated by Django 5.2.1 on 2025-05-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesFromBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('author_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('is_bot', models.BooleanField(default=False)),
                ('message_text', models.TextField(blank=True)),
                ('message_id', models.BigIntegerField(unique=True)),
                ('message_type', models.CharField(max_length=50)),
                ('info', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
    ]
