# Generated by Django 5.2.1 on 2025-05-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_messagesfrombot'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='messagesfrombot',
            table='new_messages',
        ),
    ]
