# Generated by Django 5.2.1 on 2025-05-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_messagesfrombot_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagesfrombot',
            options={'managed': True, 'verbose_name': 'Сообщение из чата тг', 'verbose_name_plural': 'Сообщения из чата тг'},
        ),
    ]
