# Generated by Django 5.2.1 on 2025-05-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_messagesfrombot_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesfrombot',
            name='author_id',
            field=models.IntegerField(verbose_name='id автора'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='info',
            field=models.TextField(blank=True, verbose_name='Инфо'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='is_bot',
            field=models.BooleanField(default=False, verbose_name='Это бот'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='message_id',
            field=models.BigIntegerField(unique=True, verbose_name='id сообщения'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='message_text',
            field=models.TextField(blank=True, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='message_type',
            field=models.CharField(max_length=50, verbose_name='Тип сообщения'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Время сообщения'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='username автора'),
        ),
    ]
