# Generated by Django 5.2.1 on 2025-05-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_messagesfrombot_author_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagesfrombot',
            options={'verbose_name': 'Сообщение из чата тг', 'verbose_name_plural': 'Сообщения из чата тг'},
        ),
        migrations.AlterModelTable(
            name='messagesfrombot',
            table=None,
        ),
    ]
