# Generated by Django 5.2.1 on 2025-05-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_messagesfrombot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesfrombot',
            name='chat_id',
            field=models.BigIntegerField(default=-1002511000091, verbose_name='id чата'),
        ),
        migrations.AlterUniqueTogether(
            name='messagesfrombot',
            unique_together={('chat_id', 'message_id')},
        ),
    ]
