# Generated by Django 5.2.1 on 2025-05-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_messagesfrombot_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesfrombot',
            name='chat_id',
            field=models.BigIntegerField(verbose_name='id чата'),
        ),
    ]
