# Generated by Django 5.2.1 on 2025-06-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_messagesfrombot_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('question_number', models.IntegerField(unique=True, verbose_name='Номер вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='TextSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название шаблона')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текстовый шаблон',
                'verbose_name_plural': 'Текстовые шаблоны',
            },
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True, verbose_name='id покупки')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время покупки')),
                ('username', models.CharField(db_index=True, max_length=30, verbose_name='Кто купил')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='id фолловера')),
                ('ready', models.BooleanField(default=False, verbose_name='Выполнили')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заказ випки',
                'verbose_name_plural': 'Заказы випок',
            },
        ),
        migrations.AddField(
            model_name='url',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='message_id',
            field=models.BigIntegerField(verbose_name='id сообщения'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='Выполнили'),
        ),
    ]
