# Generated by Django 5.2.1 on 2025-06-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_questionandanswer_textsample_vip_url_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.TextField(verbose_name='Название фильма')),
                ('film_year', models.CharField(max_length=20, verbose_name='Год фильма')),
                ('top_on_auction', models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='Топ на ауке')),
                ('chance_to_win', models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='Шанс на выигрыш')),
                ('winners_nicknames', models.TextField(blank=True, default='-', verbose_name='Чей фильм победил')),
                ('auction_date', models.DateField(verbose_name='Дата аукциона')),
                ('view_type', models.CharField(choices=[('аук', 'аук'), ('выкуп', 'выкуп')], default='Аук', max_length=10, verbose_name='Аук или выкуп')),
                ('kinopoisk_id', models.CharField(max_length=10, verbose_name='id фильма на кинопоиске')),
                ('rating_kinopoisk', models.FloatField(blank=True, null=True, verbose_name='Оценка фильма на кинопоиске')),
                ('rating_imdb', models.FloatField(blank=True, null=True, verbose_name='Оценка фильма на IMDb')),
                ('auction_type', models.CharField(choices=[('балловый', 'балловый'), ('денежный', 'денежный'), ('смешанный', 'смешанный'), ('-', '-')], default='Аук', max_length=10, verbose_name='Тип аука')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать ли в публичном списке')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['auction_date'],
            },
        ),
        migrations.CreateModel(
            name='FilmForWatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('kinopoisk_id', models.IntegerField(verbose_name='id фильма на кинопоиске')),
                ('name', models.CharField(blank=True, db_index=True, default='Новый фильм', null=True, verbose_name='Название фильма')),
                ('poster_url_preview', models.CharField(blank=True, null=True, verbose_name='Ссылка на постер фильма')),
                ('rating_kinopoisk', models.FloatField(blank=True, max_length=10, null=True, verbose_name='Рейтинг на кинопоиске')),
                ('rating_imdb', models.FloatField(blank=True, max_length=10, null=True, verbose_name='Рейтинг на IMDb')),
                ('film_length', models.CharField(blank=True, max_length=10, null=True, verbose_name='Длительность фильма')),
                ('film_year', models.IntegerField(blank=True, null=True, verbose_name='Год фильма')),
                ('film_genres', models.CharField(blank=True, null=True, verbose_name='Список жанров')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Описание фильма')),
            ],
            options={
                'verbose_name': 'Фильм на просмотр',
                'verbose_name_plural': 'Фильмы на просмотр',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('info', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
