# Generated by Django 5.2.1 on 2025-06-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_film_filmforwatching_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать ли в публичном списке'),
        ),
    ]
