# Generated by Django 5.2.1 on 2025-07-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_roulette_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesfrombot',
            name='info',
        ),
        migrations.AddField(
            model_name='messagesfrombot',
            name='reply_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='id сообщения на ответ'),
        ),
        migrations.AddField(
            model_name='messagesfrombot',
            name='stickerpack_name',
            field=models.CharField(blank=True, null=True, verbose_name='Название стикерпака'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='full_name',
            field=models.CharField(verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='message_type',
            field=models.CharField(verbose_name='Тип сообщения'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='username',
            field=models.CharField(blank=True, null=True, verbose_name='username автора'),
        ),
    ]
