# Generated by Django 5.2.1 on 2025-10-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_messagesfrombot_info_messagesfrombot_reply_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(unique=True, verbose_name='id автора')),
                ('author_name', models.CharField(verbose_name='Имя автора')),
                ('image_count', models.IntegerField(default=0, verbose_name='фото')),
                ('video_count', models.IntegerField(default=0, verbose_name='видео')),
                ('repost_count', models.IntegerField(default=0, verbose_name='видео')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Это модератор')),
            ],
            options={
                'verbose_name': 'Лимит по чату тг',
                'verbose_name_plural': 'Лимиты по чату тг',
            },
        ),
    ]
