# Generated by Django 5.2.1 on 2025-10-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_medialimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialimit',
            name='other_clips_count',
            field=models.IntegerField(default=0, verbose_name='прочие клипы'),
        ),
        migrations.AddField(
            model_name='medialimit',
            name='yrarami_clips_count',
            field=models.IntegerField(default=0, verbose_name='клипы урарами'),
        ),
        migrations.AlterField(
            model_name='medialimit',
            name='repost_count',
            field=models.IntegerField(default=0, verbose_name='репосты'),
        ),
    ]
