# Generated by Django 5.2.1 on 2025-11-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_medialimit_other_clips_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesfrombot',
            name='author_id',
            field=models.IntegerField(db_index=True, verbose_name='id автора'),
        ),
    ]
