# Generated by Django 5.2.1 on 2025-11-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_messagesfrombot_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название флага')),
                ('is_active', models.BooleanField(default=False, verbose_name='Состояние флага')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения флага')),
            ],
            options={
                'verbose_name': 'Флаг',
                'verbose_name_plural': 'Флаги',
            },
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(unique=True, verbose_name='id автора')),
                ('author_name', models.CharField(verbose_name='Имя автора')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата выполнения команды')),
                ('counter', models.IntegerField(default=0, verbose_name='Количество вызовов команды')),
            ],
            options={
                'verbose_name': 'Команда Love',
                'verbose_name_plural': 'Команды Love',
            },
        ),
    ]
