# Generated by Django 5.2.1 on 2025-11-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_flags_love'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flags',
            new_name='Flag',
        ),
    ]
