# Generated by Django 5.2.1 on 2025-11-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_flags_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesfrombot',
            name='author_id',
            field=models.BigIntegerField(db_index=True, verbose_name='id автора'),
        ),
    ]
