# Generated by Django 5.2.1 on 2025-12-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_messagesfrombot_author_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messagesfrombot',
            index=models.Index(fields=['chat_id', 'timestamp'], name='main_messag_chat_id_9b847c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagesfrombot',
            index=models.Index(fields=['chat_id', 'author_id'], name='main_messag_chat_id_a1821e_idx'),
        ),
    ]
