# Generated by Django 5.2.1 on 2025-12-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_messagesfrombot_main_messag_chat_id_9b847c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialimit',
            name='gif_count',
            field=models.IntegerField(default=0, verbose_name='gif'),
        ),
    ]
