# Generated by Django 5.2.1 on 2025-12-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_medialimit_gif_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время бана')),
                ('author_id', models.BigIntegerField(unique=True, verbose_name='id автора')),
                ('full_name', models.CharField(verbose_name='Имя автора')),
                ('username', models.CharField(blank=True, null=True, verbose_name='username автора')),
                ('message_text', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('message_id', models.BigIntegerField(verbose_name='id сообщения')),
                ('spam_patterns', models.TextField(blank=True, verbose_name='Спам паттерны')),
            ],
            options={
                'verbose_name': 'Забаненный пользователь тг',
                'verbose_name_plural': 'Забаненные пользователи тг',
            },
        ),
    ]
