# Generated by Django 5.2.1 on 2025-12-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_banneduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchAppToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название токена')),
                ('access_token', models.TextField(verbose_name='Access token')),
                ('refreshed_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления токена')),
                ('expires_at', models.DateTimeField(verbose_name='Дата и время истечения токена')),
            ],
            options={
                'verbose_name': 'Twitch app token',
                'verbose_name_plural': 'Twitch app tokens',
            },
        ),
    ]
