# Generated by Django 5.2.1 on 2025-12-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_twitchapptoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('stream.online', 'Stream online'), ('stream.offline', 'Stream offline')], db_index=True, max_length=50)),
                ('subscription_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения подписки')),
            ],
            options={
                'verbose_name': 'Twitch subscription',
                'verbose_name_plural': 'Twitch subscriptions',
                'unique_together': {('event_type',)},
            },
        ),
    ]
