# Generated by Django 5.2.1 on 2026-01-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_twitchsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(max_length=100, unique=True, verbose_name='ID стрима')),
                ('channel_name', models.CharField(max_length=100, verbose_name='Канал')),
                ('title', models.CharField(max_length=200, verbose_name='Название стрима')),
                ('started_at', models.DateTimeField(verbose_name='Время начала')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Продолжительность')),
            ],
        ),
    ]
