# Generated by Django 5.2.1 on 2026-01-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_twitchstream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchsubscription',
            name='expires_at',
        ),
    ]
