# Generated by Django 5.2.1 on 2026-01-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_twitchbottoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('message_id', models.CharField(max_length=100)),
                ('reply_to_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('is_mod', models.BooleanField(default=False)),
                ('is_subscriber', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='main_twitch_created_5fbd8c_idx'), models.Index(fields=['user_id'], name='main_twitch_user_id_46e4c6_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel_name', 'message_id'), name='uniq_channel_message')],
            },
        ),
    ]
