# Generated by Django 5.2.1 on 2026-01-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_twitchchatmessage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='twitchchatmessage',
            name='uniq_channel_message',
        ),
        migrations.AddConstraint(
            model_name='twitchchatmessage',
            constraint=models.UniqueConstraint(fields=('channel_name', 'message_id'), name='uniq_channel_message'),
        ),
    ]
