# Generated by Django 5.2.1 on 2026-01-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_twitchchatmessage_uniq_channel_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitchChatMessage',
        ),
    ]
