# Generated by Django 5.2.1 on 2026-01-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_twitchchatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitchchatmessage',
            options={'verbose_name': 'Сообщение с твича', 'verbose_name_plural': 'Сообщения с твича'},
        ),
        migrations.AlterModelOptions(
            name='twitchstream',
            options={'verbose_name': 'Twitch стрим', 'verbose_name_plural': 'Twitch стримы'},
        ),
        migrations.RemoveField(
            model_name='twitchstream',
            name='channel_name',
        ),
    ]
