# Generated by Django 5.2.1 on 2026-01-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_twitchchatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchchatmessage',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='twitchchatmessage',
            name='first_message',
            field=models.BooleanField(default=False),
        ),
    ]
