# Generated by Django 5.2.1 on 2026-01-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_twitchchatmessage_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='love',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата выполнения команды'),
        ),
    ]
