# Generated by Django 5.2.1 on 2026-01-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_love_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_id', models.IntegerField(unique=True, verbose_name='id доната')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время доната')),
                ('username', models.CharField(db_index=True, max_length=30, verbose_name='Никнейм донатера')),
                ('amount_main', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма доната в рублях')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма доната')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('is_commission_covered', models.BooleanField(verbose_name='Покрыта ли комиссия')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('media_data', models.TextField(default='', verbose_name='Дополнительные данные')),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
            },
        ),
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='channel_name',
            field=models.CharField(max_length=100, verbose_name='Название канала'),
        ),
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет ника'),
        ),
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='created_at',
            field=models.DateTimeField(verbose_name='Время сообщения'),
        ),
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя в чате'),
        ),
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='first_message',
            field=models.BooleanField(default=False, verbose_name='Это первое сообщение'),
        ),
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='is_mod',
            field=models.BooleanField(default=False, verbose_name='Это модер'),
        ),
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='is_subscriber',
            field=models.BooleanField(default=False, verbose_name='Это подписчик'),
        ),
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Это вип'),
        ),
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='message',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='message_id',
            field=models.CharField(max_length=100, verbose_name='id сообщения'),
        ),
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='reply_to_message_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id сообщения на ответ'),
        ),
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='user_id',
            field=models.BigIntegerField(verbose_name='id автора'),
        ),
        migrations.AlterField(
            model_name='twitchchatmessage',
            name='username',
            field=models.CharField(max_length=100, verbose_name='username автора'),
        ),
    ]
