# Generated by Django 5.2.1 on 2026-01-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_donate_alter_twitchchatmessage_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='media_data',
            field=models.TextField(default='', null=True, verbose_name='Дополнительные данные'),
        ),
    ]
