# Generated by Django 5.2.1 on 2026-01-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_donate_media_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='media_data',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительные данные'),
            preserve_default=False,
        ),
    ]
