# Generated by Django 5.2.1 on 2026-02-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_donate_media_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Логин')),
                ('nickname', models.CharField(db_index=True, max_length=50, verbose_name='Никнейм')),
                ('old_nicknames', models.JSONField(blank=True, default=list, verbose_name='Старые ники')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('creation_date', models.DateField(verbose_name='Дата регистрации')),
                ('view_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата отслеживания yrarami')),
                ('twitch_id', models.IntegerField(unique=True, verbose_name='twitch id')),
                ('fakes', models.JSONField(blank=True, default=dict, verbose_name='Фэйковые аккаунты')),
                ('telegram_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='twitch id')),
                ('telegram_nickname', models.CharField(blank=True, default='', max_length=50, verbose_name='Телеграм никнейм')),
                ('telegram_tag', models.CharField(blank=True, default='', max_length=50, verbose_name='Телеграм тэг')),
                ('vip_channel', models.JSONField(blank=True, default=list, verbose_name='Где является випом')),
                ('moderator_channel', models.JSONField(blank=True, default=list, verbose_name='Где является модером')),
                ('streamer', models.BooleanField(default=False, verbose_name='Является ли стримером')),
                ('contentmaker', models.BooleanField(default=False, verbose_name='Является ли контентмейкером')),
                ('ban', models.CharField(choices=[('без бана', 'без бана'), ('бан у yrarami', 'бан у yrarami'), ('бан на твиче', 'бан на твиче')], default='без бана', max_length=20, verbose_name='Бан')),
                ('prev_moderator', models.JSONField(blank=True, default=list, verbose_name='Где был модером')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать ли юзера в публичном списке')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
                'ordering': ['nickname'],
            },
        ),
    ]
