# Generated by Django 5.2.1 on 2026-02-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='prev_moderator_yrarami',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Был модером у yrarami'),
        ),
        migrations.AddField(
            model_name='follower',
            name='top_donater',
            field=models.BooleanField(default=False, verbose_name='Является ли топ донатером'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='telegram id'),
        ),
    ]
