# Generated by Django 5.2.1 on 2026-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_follower_prev_moderator_yrarami_follower_top_donater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='color',
            field=models.CharField(choices=[('danger', 'Опасный/Забанен'), ('suspicious', 'Подозрительный'), ('neutral', 'Нейтральный'), ('good', 'Классный чатерс')], default='neutral', max_length=20, verbose_name='Цвет карточки'),
        ),
    ]
