# Generated by Django 5.2.1 on 2026-03-20 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_follower_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True, verbose_name='id события')),
                ('action_type', models.CharField(choices=[('BAN', 'Ban'), ('TIMEOUT', 'Timeout'), ('UNBAN', 'Unban'), ('UNTIMEOUT', 'Untimeout')], db_index=True, max_length=10, verbose_name='тип события')),
                ('user_id', models.CharField(db_index=True, max_length=50, verbose_name='id юзера')),
                ('user_login', models.CharField(max_length=255, verbose_name='login юзера')),
                ('user_name', models.CharField(max_length=255, verbose_name='имя юзера')),
                ('broadcaster_user_id', models.CharField(db_index=True, max_length=50, verbose_name='id стримера')),
                ('broadcaster_user_login', models.CharField(max_length=255, verbose_name='login стримера')),
                ('broadcaster_user_name', models.CharField(max_length=255, verbose_name='имя стримера')),
                ('moderator_user_id', models.CharField(max_length=50, verbose_name='id модератора')),
                ('moderator_user_login', models.CharField(max_length=255, verbose_name='login модератора')),
                ('moderator_user_name', models.CharField(max_length=255, verbose_name='имя модератора')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='причина бана/мута')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='дата окончания мута')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='срок мута')),
                ('event_datetime', models.DateTimeField(db_index=True, verbose_name='время события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время записи в базу')),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='follower',
            name='color',
            field=models.CharField(choices=[('danger', 'Опасный'), ('suspicious', 'Подозрительный'), ('neutral', 'Нейтральный'), ('good', 'Классный чатерс')], default='neutral', max_length=20, verbose_name='Цвет карточки'),
        ),
        migrations.AlterField(
            model_name='twitchsubscription',
            name='event_type',
            field=models.CharField(choices=[('stream.online', 'Stream online'), ('stream.offline', 'Stream offline'), ('channel.ban', 'Channel ban'), ('channel.unban', 'Channel unban')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='twitchchatmessage',
            index=models.Index(fields=['channel_name', 'user_id', '-created_at'], name='main_twitch_channel_5e3ad2_idx'),
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to='main.moderationevent'),
        ),
        migrations.AddIndex(
            model_name='moderationevent',
            index=models.Index(fields=['user_id'], name='main_modera_user_id_45ee7d_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationevent',
            index=models.Index(fields=['broadcaster_user_id'], name='main_modera_broadca_4ca021_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationevent',
            index=models.Index(fields=['action_type'], name='main_modera_action__4871be_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationevent',
            index=models.Index(fields=['resolved'], name='main_modera_resolve_7140a5_idx'),
        ),
    ]
