# Generated by Django 5.2.1 on 2026-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_moderationevent_alter_follower_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='test_donate',
            field=models.BooleanField(default=False, verbose_name='Тестовый донат'),
        ),
    ]
