# Generated by Django 5.2.1 on 2026-09-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_donate_test_donate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannedUser',
        ),
        migrations.DeleteModel(
            name='Donate',
        ),
        migrations.DeleteModel(
            name='Flag',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Love',
        ),
        migrations.DeleteModel(
            name='MediaLimit',
        ),
        migrations.RemoveField(
            model_name='moderationevent',
            name='resolved_by',
        ),
        migrations.DeleteModel(
            name='QuestionAndAnswer',
        ),
        migrations.DeleteModel(
            name='TwitchAppToken',
        ),
        migrations.DeleteModel(
            name='TwitchBotToken',
        ),
        migrations.DeleteModel(
            name='TwitchChatMessage',
        ),
        migrations.DeleteModel(
            name='TwitchStream',
        ),
        migrations.DeleteModel(
            name='TwitchSubscription',
        ),
        migrations.DeleteModel(
            name='Vip',
        ),
        migrations.DeleteModel(
            name='ModerationEvent',
        ),
    ]
