# Generated by Django 5.2.1 on 2026-09-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_unused_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmforwatching',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Описание фильма'),
        ),
        migrations.AlterField(
            model_name='filmforwatching',
            name='film_genres',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Список жанров'),
        ),
        migrations.AlterField(
            model_name='filmforwatching',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='Новый фильм', max_length=255, null=True, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='filmforwatching',
            name='poster_url_preview',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на постер фильма'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='message_type',
            field=models.CharField(max_length=50, verbose_name='Тип сообщения'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='stickerpack_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название стикерпака'),
        ),
        migrations.AlterField(
            model_name='messagesfrombot',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='username автора'),
        ),
    ]
